# Datos maestros de líneas y estaciones
lines_data = {
    "R1": {
        "color": "#1E88E5",
        "stations": [
            "L’Hospitalet de Llobregat",
            "Barcelona‑Sants",
            "Barcelona – Plaça de Catalunya",
            "Barcelona – Arc de Triomf",
            "Barcelona – El Clot / El Clot‑Aragó",
            "Sant Adrià de Besòs",
            "Badalona",
            "Montgat",
            "Montgat Nord",
            "El Masnou / Ocata",
            "Premià de Mar",
            "Vilassar de Mar",
            "Cabrera de Mar",
            "Mataró",
            "Sant Andreu de Llavaneres",
            "Caldes d’Estrac",
            "Arenys de Mar",
            "Canet de Mar",
            "Sant Pol de Mar",
            "Calella",
            "Pineda de Mar",
            "Santa Susanna",
            "Malgrat de Mar",
            "Blanes",
            "Tordera",
            "Maçanet‑Massanes"
        ]
    },
    "R2": {
        "color": "#43A047",
        "stations": [
            "Sant Vicenç de Calders",
            "Vilanova i la Geltrú",
            "Sitges",
            "Garraf",
            "Platja de Castelldefels",
            "Castelldefels",
            "Gavà",
            "Viladecans",
            "El Prat de Llobregat",
            "Bellvitge | Gornal",
            "Barcelona – Sants",
            "Barcelona – Passeig de Gràcia",
            "Barcelona – El Clot",
            "Barcelona – Estació de França",
            "Barcelona – Sant Andreu",
            "Montcada i Reixac",
            "La Llagosta",
            "Mollet – Sant Fost",
            "Montmeló",
            "Granollers Centre",
            "Les Franqueses – Granollers Nord",
            "Cardedeu",
            "Llinars del Vallès",
            "Palautordera",
            "Sant Celoni",
            "Gualba",
            "Riells i Viabrea – Breda",
            "Hostalric",
            "Maçanet‑Massanes"
        ]
    },
    "R3": {
        "color": "#FDD835",
        "stations": [
            "L’Hospitalet de Llobregat",
            "Barcelona - Sants",
            "Barcelona - Plaça de Catalunya",
            "Barcelona - Arc de Triomf",
            "Barcelona - La Sagrera‑Meridiana",
            "Barcelona - Fabra i Puig",
            "Barcelona - Torre Baró | Vallbona",
            "Montcada Bifurcació",
            "Montcada Ripollet",
            "Santa Perpètua de Mogoda – La Florida",
            "Mollet Santa Rosa",
            "Parets del Vallès",
            "Granollers - Canovelles",
            "Les Franqueses del Vallès",
            "La Garriga",
            "Figaró",
            "Sant Martí de Centelles",
            "Centelles",
            "Balenyà - Els Hostalets",
            "Balenyà - Tona - Seva",
            "Vic",
            "Manlleu",
            "Torelló",
            "Borgonyà",
            "Sant Quirze de Besora",
            "La Farga de Bebié",
            "Ripoll",
            "Campdevànol",
            "Ribes de Freser",
            "Planoles",
            "Toses",
            "La Molina",
            "Urtx - Alp",
            "Puigcerdà",
            "La Tor de Querol – Enveig"
        ]
    },
    "R4": {
        "color": "#E64A19",
        "stations": [
            "Sant Vicenç de Calders",
            "El Vendrell",
            "L’Arboç",
            "Els Monjos",
            "Vilafranca del Penedès",
            "La Granada",
            "Lavern‑Subirats",
            "Sant Sadurní d’Anoia",
            "Gelida",
            "Martorell Central",
            "Castellbisbal",
            "El Papiol",
            "Molins de Rei",
            "Sant Feliu de Llobregat",
            "Sant Joan Despí",
            "Cornellà",
            "L’Hospitalet de Llobregat",
            "Barcelona – Sants",
            "Barcelona – Plaça de Catalunya",
            "Barcelona – Arc de Triomf",
            "Barcelona – La Sagrera‑Meridiana",
            "Barcelona – Torre Baró | Vallbona",
            "Barcelona – Sant Andreu Arenal",
            "Montcada i Reixac – Sta. Maria",
            "Montcada i Reixac – Manresa",
            "Montcada Bifurcació",
            "Cerdanyola del Vallès",
            "Barberà del Vallès",
            "Sabadell Nord",
            "Sabadell Centre",
            "Sabadell Sud",
            "Terrassa Est",
            "Terrassa Estació del Nord",
            "Sant Miquel de Gonteres",
            "Viladecavalls",
            "Vacarisses‑Torreblanca",
            "Vacarisses",
            "Castellbell i el Vilar – Monistrol de Montserrat",
            "Sant Vicenç de Castellet",
            "Manresa"
        ]
    }
}
